services:

    swd_core_db:
        class: Swd\CoreBundle\Database\Database
        arguments: ["%database_host%", "%database_name%", "%database_user%", "%database_password%"]

    swd_core_user_service:
        class: Swd\CoreBundle\Services\UserService
        arguments: ["@swd_core_db", "@security.encoder_factory"]

    swd_core_role_service:
        class: Swd\CoreBundle\Services\RoleService
        arguments: ["@swd_core_db"]