login:
    path:     /admin/security/login
    defaults: { _controller: SecuredBundle:Login:login }
login_check:
    path:  /admin/security/login_check
logout:
    path: /admin/security/logout
forgot_password:
    path:     /admin/security/login
    defaults: { _controller: SecuredBundle:Login:login }
swd_admin_user_list:
    path:     /admin/user/list
    defaults: { _controller: SecuredBundle:User:list }
swd_admin_get_user_list:
    path:     /admin/user/get_list
    defaults: { _controller: SecuredBundle:User:getList }
swd_admin_user:
    path:     /admin/user/{id}
    defaults: { _controller: SecuredBundle:User:form }

