# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        Swd\CoreBundle\Object\User:
            algorithm: bcrypt
            cost: 12

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        swd_user_provider:
            id: swd_user_provider

    firewalls:

        secured_area:
            pattern: ^/admin
            anonymous: ~
            form_login:
                check_path: /admin/security/login_check
                login_path: /admin/security/login
                provider: swd_user_provider
                #success_handler: swd_security_login_success
            logout:
                path: /admin/security/logout
                target: /admin/security/login
                handlers: [swd_security_logout]

        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js|admin_theme|kendoui|w2ui-1.5.rc1)/
            security: false

    access_control:
        - { path: ^/admin/security/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
