parameters:
  security_params:
    refreshCaching: true
    refreshesAllowed: 5

services:

    swd_user_provider:
        class: Swd\SecuredBundle\Providers\UserProvider
        arguments: ['@swd_core_user_service']
    swd_security_logout:
        class: Swd\SecuredBundle\Handlers\LogoutHandler
        arguments: ['@session']
    swd_security_user_voter:
        class: Swd\SecuredBundle\Voters\UserVoter
        arguments: ['@security.access.decision_manager']
        tags:
            - { name: security.voter }
        # small performance boost
        public: false
    swd_security_user_type:
        class: Swd\SecuredBundle\Forms\UserType
        arguments: ['@service_container']
        tags:
            - { name: form.type }
