parameters:
  security_params:
    refreshCaching: true
    refreshesAllowed: 5

services:

    platform.user.manager:
        class: Doctrine\ORM\EntityManager
        factory: ['@doctrine','getManagerForClass']
        arguments: ['Swd\CoreBundle\Entity\User']
    platform.user.repository:
        class: Swd\SecuredBundle\Repository\UserRepository
        factory: ['@platform.user.manager','getRepository']
        arguments: ['Swd\CoreBundle\Entity\User']
    platform.user_role.manager:
        class: Doctrine\ORM\EntityManager
        factory: ['@doctrine','getManagerForClass']
        arguments: ['Swd\CoreBundle\Entity\UserRole']
    platform.user_role.repository:
        class: Swd\SecuredBundle\Repository\UserRepository
        factory: ['@platform.user.manager','getRepository']
        arguments: ['Swd\CoreBundle\Entity\UserRole']
    swd_user_provider:
        class: Swd\SecuredBundle\Providers\UserProvider
        arguments: ['@swd_core_user_service']
    swd_security_logout:
        class: Swd\SecuredBundle\Handlers\LogoutHandler
        arguments: ['@session']
