parameters:
  swd.security_success_handler.class: Swd\SecuredBundle\Handlers\SuccessHandler
  security_params:
    refreshCaching: true
    refreshesAllowed: 5

services:

    platform.user.manager:
        class: Doctrine\ORM\EntityManager
        factory: ['@doctrine','getManagerForClass']
        arguments: ['Swd\SecuredBundle\Entity\User']
    platform.user.repository:
        class: Swd\SecuredBundle\Repository\UserRepository
        factory: ['@platform.user.manager','getRepository']
        arguments: ['Swd\SecuredBundle\Entity\User']
    platform.user_role.manager:
        class: Doctrine\ORM\EntityManager
        factory: ['@doctrine','getManagerForClass']
        arguments: ['Swd\SecuredBundle\Entity\UserRole']
    platform.user_role.repository:
        class: Swd\SecuredBundle\Repository\UserRepository
        factory: ['@platform.user.manager','getRepository']
        arguments: ['Swd\SecuredBundle\Entity\UserRole']
    swd_user_provider:
        class: Swd\SecuredBundle\Providers\UserProvider
        arguments: ['@platform.user.repository', '@platform.user_role.repository']
